"""
Project Euler - Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

latest = 0
f = [1,2]
MAX = 4000000
while latest <= MAX:
    latest = f[-2] + f[-1]
    if latest < MAX:
        f.append(latest)
print sum([e for e in f if e % 2 == 0])
